# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [3]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.8957, 0.9542, 0.2557, 0.2891, 0.3391, 0.7926, 0.1204],
        [0.5821, 0.5559, 0.2957, 0.1793, 0.0132, 0.5294, 0.4575],
        [0.0711, 0.2344, 0.9611, 0.5393, 0.5913, 0.6499, 0.3580],
        [0.5794, 0.4665, 0.4262, 0.3492, 0.2810, 0.5742, 0.7881],
        [0.8737, 0.5669, 0.7404, 0.3235, 0.2083, 0.2576, 0.9743],
        [0.2169, 0.2225, 0.6443, 0.2570, 0.0517, 0.7549, 0.4414],
        [0.0909, 0.5230, 0.5632, 0.1437, 0.6940, 0.8040, 0.1089]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
y = torch.rand(1, 7)
print(y)
x @ y.transpose(0, 1)

# Perform matrix multiplication 


tensor([[0.2233, 0.6671, 0.5634, 0.0331, 0.7988, 0.8078, 0.7598]])


tensor([[1.9928],
        [1.4590],
        [2.0008],
        [1.9793],
        [2.1158],
        [1.5548],
        [1.9777]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7, 7)
y = torch.rand(1, 7)

# Matrix multiply tensors
x @ y.transpose(0, 1)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
torch.mps.device_count()



1

In [9]:
# Create two random tensors on GPU
x6 = torch.rand(2, 3, device="mps")
x5 = torch.rand(2, 3, device="mps")



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
x7 = torch.matmul(x6, x6.T)
x7

tensor([[1.4948, 0.9231],
        [0.9231, 1.0608]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
x7.max(), x7.min()
# Find min


(tensor(1.6431, device='mps:0'), tensor(0.8262, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max

torch.argmax(x7), torch.argmin(x7)
# Find arg min


(tensor(2, device='mps:0'), tensor(1, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x10 = torch.rand((1,1,1,10), device="mps")


# Remove single dimensions
x10.squeeze()

# Print out tensors and their shapes
print(f"x10 shape before squeeze: {x10.shape}")
print(f"x10 shape after squeeze: {x10.squeeze().shape}")

x10 shape before squeeze: torch.Size([1, 1, 1, 10])
x10 shape after squeeze: torch.Size([10])
